name: Deploy to AWS

on:
    workflow_dispatch:
      inputs:
        branch:
          description: 'Branch to deploy'
          required: true
          default: 'main'
        environment:
          description: 'Environment to deploy to'
          required: true
          default: 'development-app1'
          type: choice
          options:
            - development-app1
            - uat-app1
            - prod-app1
        application:
          description: 'Application to deploy'
          required: true
          default: 'app2'
          type: choice
          options:
            - app1
            - app2
jobs:
    terraform:
      name: Terraform Plan and Apply
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5 
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
  
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Format
        run: terraform fmt -check
  
      - name: Terraform Validate
        run: terraform validate
  
      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan -out=plan.tfplan
  
    manual_approval:
      name: Manual Approval
      needs: terraform
      runs-on: ubuntu-latest
      environment:
        name: ${{ github.event.inputs.environment }}
        url: https://dev.app1-oars.com/internallogin # Optional: URL for more information
      steps:
      - name: Awaiting Approval
        run: echo "Waiting for manual approval to apply Terraform changes to the ${{ github.event.inputs.environment }} environment"
  
    apply_terraform:
      name: Apply Terraform
      needs: manual_approval
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
  
      - name: Apply Terraform
        run: terraform apply -auto-approve plan.tfplan
  