name: CI

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/dev/dev_app2/*.tf' 
      ## - 'terraform/dev/dev_app2/*.tfvars'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Print GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "GitHub Context : - : "
          echo "$GITHUB_CONTEXT"
